#!/usr/bin/env python3
"""Generate color-specific BoxFerry SVG assets from centralized CSS tokens."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKEN_FILE = Path("content/assets/stylesheets/tokens.css")
MARK_SOURCE = Path("content/assets/images/brand/boxferry-mark.svg")
WORDMARK_SOURCE = Path("content/assets/images/brand/boxferry-wordmark.svg")
GENERATED_DIRECTORY = Path("content/assets/images/brand/generated")
GENERATED_ASSET_PATHS = (
    Path("content/assets/images/favicon.svg"),
    GENERATED_DIRECTORY / "boxferry-mark-dark.svg",
    GENERATED_DIRECTORY / "boxferry-mark-light.svg",
    GENERATED_DIRECTORY / "boxferry-wordmark-dark.svg",
    GENERATED_DIRECTORY / "boxferry-wordmark-light.svg",
    GENERATED_DIRECTORY / "boxferry-social-dark.svg",
    GENERATED_DIRECTORY / "boxferry-social-light.svg",
)
REQUIRED_COLORS = (
    "--bf-brand-primary",
    "--bf-brand-secondary",
    "--bf-brand-accent",
    "--bf-background",
    "--bf-surface",
    "--bf-text",
    "--bf-text-muted",
)
COLOR_PATTERN = re.compile(r"#[0-9a-fA-F]{6,8}\b")
TOKEN_PATTERN = re.compile(r"^\s*(--bf-[a-z0-9-]+):\s*(#[0-9a-fA-F]{6,8});\s*$", re.MULTILINE)


class BrandAssetError(RuntimeError):
    """Describe invalid brand-token or vector-source input."""


def parse_palettes(token_source: str) -> dict[str, dict[str, str]]:
    """Read required dark and light colors from the token stylesheet."""
    palettes: dict[str, dict[str, str]] = {}
    for name, scheme in (("dark", "slate"), ("light", "default")):
        match = re.search(
            rf'\[data-md-color-scheme="{scheme}"\]\s*\{{(?P<body>.*?)\n\}}',
            token_source,
            re.DOTALL,
        )
        if match is None:
            raise BrandAssetError(f"missing {name} color-scheme block")
        pairs = TOKEN_PATTERN.findall(match.group("body"))
        colors = dict(pairs)
        if len(colors) != len(pairs):
            raise BrandAssetError(f"duplicate color token in {name} color-scheme block")
        missing = [token for token in REQUIRED_COLORS if token not in colors]
        if missing:
            raise BrandAssetError(f"missing {name} color token(s): {', '.join(missing)}")
        palettes[name] = colors
    return palettes


def _source_body(source: str) -> str:
    try:
        return source.split("</title>", 1)[1].rsplit("</svg>", 1)[0].strip()
    except IndexError as error:
        raise BrandAssetError(
            "vector source must contain one title and a closing svg element"
        ) from error


def _palette_style(palette: dict[str, str]) -> str:
    return "\n".join(
        (
            "  <style>",
            f"    .bf-logo-primary {{ color: {palette['--bf-brand-primary']}; }}",
            f"    .bf-logo-secondary {{ color: {palette['--bf-brand-secondary']}; }}",
            f"    .bf-logo-accent {{ color: {palette['--bf-brand-accent']}; }}",
            f"    .bf-logo-word {{ color: {palette['--bf-text']}; }}",
            "  </style>",
        )
    )


def _colorize(source: str, palette: dict[str, str]) -> str:
    if COLOR_PATTERN.search(source):
        raise BrandAssetError("monochrome vector sources must not contain literal colors")
    marker = "</title>"
    if source.count(marker) != 1:
        raise BrandAssetError("vector source must contain exactly one title")
    return source.replace(marker, f"{marker}\n{_palette_style(palette)}", 1)


def _favicon(mark_source: str, palettes: dict[str, dict[str, str]]) -> str:
    if COLOR_PATTERN.search(mark_source):
        raise BrandAssetError("monochrome vector sources must not contain literal colors")
    dark = palettes["dark"]
    light = palettes["light"]
    style = "\n".join(
        (
            "  <style>",
            f"    .bf-logo-primary {{ color: {dark['--bf-brand-primary']}; }}",
            f"    .bf-logo-secondary {{ color: {dark['--bf-brand-secondary']}; }}",
            f"    .bf-logo-accent {{ color: {dark['--bf-brand-accent']}; }}",
            "    @media (prefers-color-scheme: light) {",
            f"      .bf-logo-primary {{ color: {light['--bf-brand-primary']}; }}",
            f"      .bf-logo-secondary {{ color: {light['--bf-brand-secondary']}; }}",
            f"      .bf-logo-accent {{ color: {light['--bf-brand-accent']}; }}",
            "    }",
            "  </style>",
        )
    )
    return mark_source.replace("</title>", f"</title>\n{style}", 1)


def _social_preview(mark_source: str, palette: dict[str, str]) -> str:
    mark = _source_body(mark_source)
    return f'''<!-- Generated by scripts/generate_brand_assets.py; do not edit. -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 1200 630"
  role="img"
  aria-labelledby="title description"
>
  <title id="title">BoxFerry social preview</title>
  <desc id="description">Source-aware Docker Compose, Podman, and Quadlet conversion</desc>
  <style>
    .bf-logo-primary {{ color: {palette["--bf-brand-primary"]}; }}
    .bf-logo-secondary {{ color: {palette["--bf-brand-secondary"]}; }}
    .bf-logo-accent {{ color: {palette["--bf-brand-accent"]}; }}
  </style>
  <rect width="1200" height="630" rx="48" fill="{palette["--bf-background"]}" />
  <rect x="52" y="52" width="1096" height="526" rx="36" fill="{palette["--bf-surface"]}" />
  <g transform="translate(104 170) scale(4)">
    {mark}
  </g>
  <text
    x="400"
    y="280"
    fill="{palette["--bf-text"]}"
    font-family="ui-sans-serif, system-ui, sans-serif"
    font-size="96"
    font-weight="750"
    letter-spacing="-4"
  >
    BoxFerry
  </text>
  <text
    x="404"
    y="355"
    fill="{palette["--bf-text-muted"]}"
    font-family="ui-sans-serif, system-ui, sans-serif"
    font-size="34"
  >
    Container definitions, carried safely.
  </text>
</svg>
'''


def render_assets(root: Path = ROOT) -> dict[Path, str]:
    """Return every generated asset as repository-relative path and content."""
    palettes = parse_palettes((root / TOKEN_FILE).read_text(encoding="utf-8"))
    mark = (root / MARK_SOURCE).read_text(encoding="utf-8")
    wordmark = (root / WORDMARK_SOURCE).read_text(encoding="utf-8")
    return {
        GENERATED_ASSET_PATHS[0]: _favicon(mark, palettes),
        GENERATED_ASSET_PATHS[1]: _colorize(mark, palettes["dark"]),
        GENERATED_ASSET_PATHS[2]: _colorize(mark, palettes["light"]),
        GENERATED_ASSET_PATHS[3]: _colorize(wordmark, palettes["dark"]),
        GENERATED_ASSET_PATHS[4]: _colorize(wordmark, palettes["light"]),
        GENERATED_ASSET_PATHS[5]: _social_preview(mark, palettes["dark"]),
        GENERATED_ASSET_PATHS[6]: _social_preview(mark, palettes["light"]),
    }


def synchronize_assets(*, check: bool, root: Path = ROOT) -> None:
    """Write assets or fail when checked assets differ from their token-derived result."""
    stale: list[Path] = []
    for relative, expected in render_assets(root).items():
        destination = root / relative
        if destination.is_file() and destination.read_text(encoding="utf-8") == expected:
            continue
        if check:
            stale.append(relative)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(expected, encoding="utf-8")
        print(f"Generated {relative.as_posix()}")
    if stale:
        paths = ", ".join(path.as_posix() for path in stale)
        raise BrandAssetError(f"generated brand assets are missing or stale: {paths}")


def main() -> int:
    """Generate or check token-derived brand assets."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing stale assets")
    arguments = parser.parse_args()
    try:
        synchronize_assets(check=arguments.check)
    except (BrandAssetError, OSError) as error:
        print(f"boxferry-website: brand asset generation failed: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        print("BoxFerry brand assets match the centralized design tokens.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
